# Generated by Django 2.2.12 on 2020-05-23 07:19

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='details',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='cv',
            name='education',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='cv',
            name='experience',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='cv',
            name='profile',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='cv',
            name='technical_skills',
            field=tinymce.models.HTMLField(),
        ),
    ]
